/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pengelompokkanjenisfluida.Boundary;

import java.io.File;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import pengelompokkanjenisfluida.Controller.DokumenManager;
import pengelompokkanjenisfluida.Controller.KMeanManager;
import pengelompokkanjenisfluida.Controller.PSOManager;
import pengelompokkanjenisfluida.Entity.FluidaMinyakBumiModel;

/**
 *
 * @author shaff
 */
public class HalamanUtama extends javax.swing.JFrame {
    private FluidaMinyakBumiModel[] fluidaMinyakBumiModels;
    /**
     * Creates new form HalamanUtama
     */
    public HalamanUtama() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_muat_data = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_data_tersedia = new javax.swing.JTable();
        btn_pso_kmeans = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_data_hasil = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tf_iterasi_pso = new javax.swing.JTextField();
        tf_partikel = new javax.swing.JTextField();
        tf_c1 = new javax.swing.JTextField();
        tf_c2 = new javax.swing.JTextField();
        tf_r1 = new javax.swing.JTextField();
        tf_r2 = new javax.swing.JTextField();
        tf_w = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel1.setText("Penggunaan PSO pada K-Means Dalam Pengelompokkan Jenis Fluida Untuk Meningkatkan Produksi Minyak Bumi");

        btn_muat_data.setText("Muat Data Excel Fluida");
        btn_muat_data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_muat_dataActionPerformed(evt);
            }
        });

        tbl_data_tersedia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Viscosity", "Api Gravity", "Salinity", "Porosity", "Permeability"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl_data_tersedia);

        btn_pso_kmeans.setText("Proses Data Menggunakan PSO-KMeans");
        btn_pso_kmeans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pso_kmeansActionPerformed(evt);
            }
        });

        tbl_data_hasil.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Viscosity", "Api Gravity", "Salinity", "Porosity", "Permeability", "EOR Fluid"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tbl_data_hasil);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Parameter PSO dan K-Means", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Agency FB", 1, 18))); // NOI18N

        jLabel2.setText("Banyak Iterasi PSO : ");

        jLabel3.setText("Banyak Partikel : ");

        jLabel4.setText("C1 : ");

        jLabel5.setText("C2 : ");

        jLabel6.setText("R1 : ");

        jLabel7.setText("R2 : ");

        jLabel8.setText("W : ");

        jLabel9.setFont(new java.awt.Font("Script MT Bold", 1, 24)); // NOI18N
        jLabel9.setText("@Putrika Purnama ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addGap(29, 29, 29)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tf_iterasi_pso)
                                    .addComponent(tf_partikel)
                                    .addComponent(tf_c1)
                                    .addComponent(tf_c2)
                                    .addComponent(tf_r1)
                                    .addComponent(tf_r2)
                                    .addComponent(tf_w, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)))
                            .addComponent(jLabel9))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tf_iterasi_pso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tf_partikel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tf_c1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tf_c2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tf_r1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tf_r2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tf_w, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(92, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(53, 53, 53))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_muat_data, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addComponent(btn_pso_kmeans, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_muat_data, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_pso_kmeans, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_muat_dataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_muat_dataActionPerformed
        // TODO add your handling code here:
        int i,j, baris;
        ArrayList<ArrayList> data;
        
        DokumenManager dokManager = new DokumenManager();
        JFileChooser fileChooser = new JFileChooser();
        int result = fileChooser.showOpenDialog(this);
        
        if(result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            String FILE_NAME = selectedFile.getAbsolutePath();
            data = dokManager.get_data(FILE_NAME);
            System.out.println("Data yang dimuat : " + selectedFile.getAbsolutePath());
            
            baris = data.size()-1;
            
            fluidaMinyakBumiModels = new FluidaMinyakBumiModel[baris];
            
            for(i=0; i<baris; i++){
                FluidaMinyakBumiModel fluidaMinyakBumiModel = new FluidaMinyakBumiModel();
                fluidaMinyakBumiModel.setViscosity(Double.parseDouble(data.get(i+1).get(0).toString()));
                fluidaMinyakBumiModel.setApi_gravity(Double.parseDouble(data.get(i+1).get(1).toString()));
                fluidaMinyakBumiModel.setSalinity(Double.parseDouble(data.get(i+1).get(2).toString()));
                fluidaMinyakBumiModel.setPorosity(Double.parseDouble(data.get(i+1).get(3).toString()));
                fluidaMinyakBumiModel.setPermeability(Double.parseDouble(data.get(i+1).get(4).toString()));
                
                fluidaMinyakBumiModels[i] = fluidaMinyakBumiModel;
            }
            
            String[] row = new String[6];
            DefaultTableModel Tabel_Jenis_Fluida = (DefaultTableModel) tbl_data_tersedia.getModel();
        
            for(i=0; i<fluidaMinyakBumiModels.length; i++){
                row[0] = String.valueOf((i+1));
                row[1] = String.valueOf(fluidaMinyakBumiModels[i].getViscosity());
                row[2] = String.valueOf(fluidaMinyakBumiModels[i].getApi_gravity());
                row[3] = String.valueOf(fluidaMinyakBumiModels[i].getSalinity());
                row[4] = String.valueOf(fluidaMinyakBumiModels[i].getPorosity());
                row[5] = String.valueOf(fluidaMinyakBumiModels[i].getPermeability());

                Tabel_Jenis_Fluida.addRow(row);
            }

            tf_partikel.setText(String.valueOf(3));
            tf_iterasi_pso.setText(String.valueOf(100));
            tf_c1.setText(String.valueOf(1));
            tf_c2.setText(String.valueOf(1));
            tf_r1.setText(String.valueOf(0.4));
            tf_r2.setText(String.valueOf(0.5));
            tf_w.setText(String.valueOf(2));
            
            JOptionPane.showMessageDialog(null, "Pemuatan data excel berhasil dilakukan.");
        }
        else{
            JOptionPane.showMessageDialog(null, "Pemuatan data gagal dilakukan.");
        }
    }//GEN-LAST:event_btn_muat_dataActionPerformed

    private void btn_pso_kmeansActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pso_kmeansActionPerformed
        // TODO add your handling code here:
        int i, iterasi_pso, iterasi_kmeans;
        double[] indexMinJarak;
        
        iterasi_pso = (int)Double.parseDouble(tf_iterasi_pso.getText());
        
        PSOManager psoManager = new PSOManager((int)Double.parseDouble(tf_partikel.getText()), Double.parseDouble(tf_w.getText()), Double.parseDouble(tf_c1.getText()), Double.parseDouble(tf_c2.getText()), Double.parseDouble(tf_r1.getText()), Double.parseDouble(tf_r2.getText()), (int)Double.parseDouble(tf_iterasi_pso.getText()));
        psoManager.inisialisasiDataPSO(fluidaMinyakBumiModels);
        psoManager.setPartikelPSO();
        
        for(i=0; i<iterasi_pso; i++){
            psoManager.hitungFitnessPSO();
            
            if(psoManager.isKondisiTerpenuhi()){
                System.out.println("iterasi berhenti : "+(i+1));
                break;
            }
            
            psoManager.updateKecepatanNPosisi();
        }
        
        KMeanManager kmeanManager = new KMeanManager(psoManager.getCentroidGbest(), fluidaMinyakBumiModels);
        indexMinJarak = kmeanManager.hitungJarakDataKeCentroid();
        
        String[] row = new String[7];
        DefaultTableModel Tabel_Hasil_Jenis_Fluida = (DefaultTableModel) tbl_data_hasil.getModel();

        for(i=0; i<indexMinJarak.length; i++){
            row[0] = String.valueOf((i+1));
            row[1] = String.valueOf(fluidaMinyakBumiModels[i].getViscosity());
            row[2] = String.valueOf(fluidaMinyakBumiModels[i].getApi_gravity());
            row[3] = String.valueOf(fluidaMinyakBumiModels[i].getSalinity());
            row[4] = String.valueOf(fluidaMinyakBumiModels[i].getPorosity());
            row[5] = String.valueOf(fluidaMinyakBumiModels[i].getPermeability());
            
            switch ((int)indexMinJarak[i]) {
                case 0:
                    fluidaMinyakBumiModels[i].setEor_fluid("Chemical Flooding");
                    break;
                case 1:
                    fluidaMinyakBumiModels[i].setEor_fluid("Combustion Flooding");
                    break;
                default:
                    fluidaMinyakBumiModels[i].setEor_fluid("Carbon Dioxide Flooding");
                    break;
            }
            
            row[6] = fluidaMinyakBumiModels[i].getEor_fluid();
            
            Tabel_Hasil_Jenis_Fluida.addRow(row);
        }
    }//GEN-LAST:event_btn_pso_kmeansActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HalamanUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HalamanUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HalamanUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HalamanUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HalamanUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_muat_data;
    private javax.swing.JButton btn_pso_kmeans;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tbl_data_hasil;
    private javax.swing.JTable tbl_data_tersedia;
    private javax.swing.JTextField tf_c1;
    private javax.swing.JTextField tf_c2;
    private javax.swing.JTextField tf_iterasi_pso;
    private javax.swing.JTextField tf_partikel;
    private javax.swing.JTextField tf_r1;
    private javax.swing.JTextField tf_r2;
    private javax.swing.JTextField tf_w;
    // End of variables declaration//GEN-END:variables
}
